name: CreaJojoPluginV1
version: '${project.version}'
main: be.creajojo.creajojopluginv1.CreaJojoPluginV1
api-version: '1.20'

commands:
  speed:
    description: Change walking speed
    usage: /<command> <multiplier>
  jump:
    description: Toggle Jump Boost effect
    usage: /<command> <0|1>